service: serverless-python311-template
frameworkVersion: "3"

plugins:
  - serverless-offline
  - serverless-python-requirements
  - serverless-prune-plugin
  - serverless-ignore
  - serverless-deployment-bucket
  - serverless-plugin-tracing

custom:
  # Serverless offline plugin
  # LINK ref: https://www.serverless.com/plugins/serverless-offline
  serverless-offline:
    httpPort: 3333
    noPrependStageInUrl: true

  # Serverless Prune Plugin
  # LINK: ref: https://www.serverless.com/plugins/serverless-prune-plugin
  prune:
    automatic: true
    number: 3

  # Serverless Deployment Bucket Plugin
  # LINK: ref: https://www.serverless.com/plugins/serverless-deployment-bucket
  deploymentBucket:
    versioning: true
    accelerate: true
    blockPublicAccess: true
    tags:
      - Key: Environment
        Value: ${self.stage}

  # Versioning Deployed Functions
  # LINK: https://www.serverless.com/framework/docs/providers/aws/guide/functions#versioning-deployed-functions
  versionFunctions: false

  # Serverless Python Requirements Plugin
  # LINK ref: https://www.serverless.com/plugins/serverless-python-requirements
  pythonRequirements:
    dockerizePip: true
    dockerSsh: true
    usePoetry: true
    slim: true
    noDeploy:
      - pytest
      - boto3
      - black
      - mypy
      - isort
      - pytest-mock
      - pytest-cov
      - taskipy
      - ruff
      - alembic
      - tox
      - pdf2image
      - ipykernel

provider:
  name: aws
  runtime: python3.11
  stage: ${opt:stage, "dev"}
  region: ap-northeast-1

  # Serverless Deployment Bucket Plugin
  # LINK ref: https://www.serverless.com/plugins/serverless-deployment-bucket
  deploymentBucket:
    name: ${self.service}-deployment-bucket-${self.stage}
    serverSideEncryption: AES256
