# api config
API_CORS_ALLOWED_ORIGINS: "http://localhost:3000"
API_BASE_URL: "http://localhost:3333/local"

# lambda powertools configs
POWERTOOLS_SERVICE_NAME: "ApiLocal"
POWERTOOLS_LOG_LEVEL: "DEBUG"
POWERTOOLS_DEV: true
POWERTOOLS_DEBUG: true
POWERTOOLS_TRACE_MIDDLEWARES: true
POWERTOOLS_TRACE_DISABLED: true
